/**
 * Mock response/grounding engine shared by the Phase 3 Copilot services.
 *
 * Centralizes "realistic" mock text generation, source attribution, and
 * citation linking so `CopilotChatService` and `CopilotRetrievalService`
 * produce consistent, deterministic-shaped (but varied) mock data without
 * duplicating generation logic.
 */

import { generateId, nowISO } from "@muse/shared";
import { Citation, Source, SourceType } from "./CopilotModels";

const FILE_TITLES = [
  "Q3 Strategy Deck.pptx",
  "Customer Success Playbook.docx",
  "Architecture Decision Record 014.md",
  "Enterprise Rollout Plan.xlsx",
  "Onboarding Runbook.docx",
];

const MEETING_TITLES = [
  "Weekly Leadership Sync",
  "Customer Escalation Review",
  "Platform Roadmap Planning",
  "1:1 with Manager",
  "Quarterly Business Review",
];

const PROJECT_TITLES = [
  "Project Aurora",
  "Copilot Enablement Initiative",
  "Customer Retention Program",
  "Platform Modernization",
  "Voice Experience Revamp",
];

const TASK_TITLES = [
  "Finalize rollout communication",
  "Review pending action items",
  "Prepare executive summary",
  "Follow up with account team",
  "Update project timeline",
];

const CONTEXT_SNIPPETS = [
  "referenced in your recent activity",
  "aligned with your current priorities",
  "based on your working context",
  "grounded in your organization's knowledge",
  "surfaced from your recent collaboration history",
];

function pick<T>(items: T[], seed: number): T {
  return items[seed % items.length];
}

/** Deterministic-ish pseudo-random seed derived from a string, for variety without true randomness. */
function seedFrom(value: string): number {
  let hash = 0;
  for (let i = 0; i < value.length; i += 1) {
    hash = (hash * 31 + value.charCodeAt(i)) >>> 0;
  }
  return hash;
}

export function buildMockSources(query: string, count = 3): Source[] {
  const seed = seedFrom(query || "muse");
  const types: SourceType[] = ["file", "meeting", "project", "task"];

  return Array.from({ length: count }, (_, index) => {
    const type = pick(types, seed + index);
    return buildMockSource(type, seed + index);
  });
}

export function buildMockSource(type: SourceType, seed: number): Source {
  const titleBank: Record<SourceType, string[]> = {
    file: FILE_TITLES,
    meeting: MEETING_TITLES,
    project: PROJECT_TITLES,
    task: TASK_TITLES,
    conversation: ["Prior conversation with MUSE"],
    context: ["Working context summary"],
  };

  const title = pick(titleBank[type], seed);
  const snippet = `[Mock] ${pick(CONTEXT_SNIPPETS, seed)}.`;

  return {
    id: generateId(`source-${type}`),
    type,
    title,
    snippet,
    url: type === "file" ? `https://m365.example.com/files/${encodeURIComponent(title)}` : undefined,
    updatedAt: nowISO(),
  };
}

export function buildCitations(sources: Source[]): Citation[] {
  return sources.map((source, index) => ({
    marker: `[${index + 1}]`,
    sourceId: source.id,
    title: source.title,
  }));
}

/**
 * Generates a realistic, grounded-sounding mock answer for a given prompt,
 * referencing the provided sources via inline citation markers.
 */
export function generateMockAnswer(prompt: string, citations: Citation[]): string {
  const trimmedPrompt = prompt.trim();
  const markers = citations.map((citation) => citation.marker).join(" ");

  const openings = [
    `Based on your Microsoft 365 context, here's what I found regarding "${trimmedPrompt}."`,
    `Here's a grounded summary in response to "${trimmedPrompt}."`,
    `Drawing on your recent files, meetings, and projects, here's my answer to "${trimmedPrompt}."`,
  ];

  const seed = seedFrom(trimmedPrompt);
  const opening = pick(openings, seed);

  const body = [
    "This response is generated by MUSE's mock Copilot engine, standing in for the real Microsoft 365 Copilot Chat API.",
    "Once real Copilot API access is enabled, this answer will be grounded in your actual enterprise data.",
  ].join(" ");

  return citations.length > 0 ? `${opening} ${body} ${markers}` : `${opening} ${body}`;
}

export function chunkAnswer(answer: string): string[] {
  // Split into small word-groups so the frontend can render a realistic
  // gradual streaming effect.
  const words = answer.split(" ");
  const chunkSize = 3;
  const chunks: string[] = [];

  for (let i = 0; i < words.length; i += chunkSize) {
    chunks.push(words.slice(i, i + chunkSize).join(" ") + (i + chunkSize < words.length ? " " : ""));
  }

  return chunks;
}
