/**
 * CopilotRetrievalService — Phase 3 mock implementation of the Microsoft
 * 365 Copilot Retrieval API surface.
 *
 * Represents enterprise-grounded search across files, meetings, projects,
 * tasks, and general work context. Never crawls Microsoft Graph directly —
 * every result here is generated by the shared mock engine.
 */

import { Logger, nowISO } from "@muse/shared";
import { RetrievalResult, Source } from "./CopilotModels";
import { buildMockSource } from "./CopilotMockEngine";
import { CopilotLogger, copilotLogger } from "./CopilotLogger";

export interface RetrievalOptions {
  query: string;
  limit?: number;
}

const DEFAULT_LIMIT = 5;

export class CopilotRetrievalService {
  private readonly logger: Logger;
  private readonly telemetry: CopilotLogger;

  constructor(logger: Logger = new Logger("muse:copilot:retrieval"), telemetry: CopilotLogger = copilotLogger) {
    this.logger = logger;
    this.telemetry = telemetry;
  }

  async searchFiles(options: RetrievalOptions): Promise<RetrievalResult> {
    return this.search(options, "file");
  }

  async searchMeetings(options: RetrievalOptions): Promise<RetrievalResult> {
    return this.search(options, "meeting");
  }

  async searchProjects(options: RetrievalOptions): Promise<RetrievalResult> {
    return this.search(options, "project");
  }

  async searchTasks(options: RetrievalOptions): Promise<RetrievalResult> {
    return this.search(options, "task");
  }

  /** General work-context search spanning all source types. */
  async searchContext(options: RetrievalOptions): Promise<RetrievalResult> {
    const limit = options.limit ?? DEFAULT_LIMIT;
    const types: Source["type"][] = ["file", "meeting", "project", "task", "context"];
    const seed = seedFrom(options.query);

    const sources = Array.from({ length: limit }, (_, index) =>
      buildMockSource(types[(seed + index) % types.length], seed + index),
    );

    this.logger.debug("searchContext", { query: options.query, count: sources.length });
    this.telemetry.logSources("retrieval", sources.length);

    return { query: options.query, sources, generatedAt: nowISO() };
  }

  private async search(options: RetrievalOptions, type: Source["type"]): Promise<RetrievalResult> {
    const limit = options.limit ?? DEFAULT_LIMIT;
    const seed = seedFrom(options.query);

    const sources = Array.from({ length: limit }, (_, index) => buildMockSource(type, seed + index));

    this.logger.debug(`search:${type}`, { query: options.query, count: sources.length });
    this.telemetry.logSources("retrieval", sources.length);

    return { query: options.query, sources, generatedAt: nowISO() };
  }
}

function seedFrom(value: string): number {
  let hash = 0;
  for (let i = 0; i < value.length; i += 1) {
    hash = (hash * 31 + value.charCodeAt(i)) >>> 0;
  }
  return hash;
}
